DOTFILES=$HOME/.dotfiles
DOTFILES_SHELL=$DOTFILES/src/shell
ZSH=$DOTFILES_SHELL/oh-my-zsh
ZSH_THEME="hyperzsh"
ZSH_CUSTOM=$DOTFILES_SHELL/zsh

# Source custom functions
source $DOTFILES_SHELL/zsh/functions/*.zsh

# Plugins list
plugins=(zsh-autosuggestions zsh-better-npm-completion zsh-nvm zsh-syntax-highlighting history-substring-search jsontools sudo urltools web-search brew brew-cask git node npm vscode yarn)

# Setup plugin `history-substring-search`
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh

# OPAM configuration
. /Users/rodolphe/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
